### ISSUE TITLE
4.3及其以下版本兼容问题

### ISSUE THREAD

**Issue by youngkaaa** [dalong982242260/PullRefresh#1]
在测试时，版本低于4.3（包括4.3）会报空指针的异常，具体看下面：

```
  Caused by: java.lang.NullPointerException
                                                                            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:548)
                                                                            at android.view.View.measure(View.java:16840)
                                                                            at cn.youngkaaa.cloudnews.widget.RingHeader.measureView(RingHeader.java:56)
                                                                            at cn.youngkaaa.cloudnews.widget.RingHeader.<init>(RingHeader.java:37)
                                                                            at cn.youngkaaa.cloudnews.widget.RingRefreshView.init(RingRefreshView.java:32)
                                                                            at cn.youngkaaa.cloudnews.widget.RingRefreshView.onFinishInflate(RingRefreshView.java:28)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:817)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                            at cn.youngkaaa.cloudnews.fragment.base.BaseFragment.onCreateView(BaseFragment.java:30)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
                                                                            at android.app.Activity.performStart(Activity.java:5387)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:168) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:177) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5493) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 



我也在找原因，如果你能找到的话更好了 
```

**Comment by yixiaolunhui** [comment]
你这个是自定义头部的时候写的有问题 ，于下拉刷新没有关系 ，

**Comment by yixiaolunhui** [comment]
你直接看demo里自定义头咋写的修改下

**Comment by youngkaaa** [comment]
好的我去看下demo

**Comment by youngkaaa** [comment]
你的demo跑起来在4.1的模拟器 和4.3的真机(三星Galaxy Ace4)上面也抛异常 

 和上面贴的的一样异常

**Comment by youngkaaa** [comment]
@dalong982242260

**Comment by yixiaolunhui** [comment]
我测试4.1虚拟机没问题，联系我qq 982242260

**Comment by Lsy1992** [comment]
问题解决了吗？
